/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUllY2pCVWhNZVF0VGZWOGhhZGZ3STBkdlczWjN0eXpOd1ZOYnZJSERWND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV2JLcmNDNU5YbWQrSTJZMzBrOFVXVDUxUXJFTDdFcTBLL1k3L3ZvaHJDMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJxS1J1L3lvSThYek80WndZOHBXU2ZoTWtqYlU4M2hYaDhWaWlGb1lZa0hvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0T3pXbmhkT3VvUVQwdTJRSXdHQ0lrcWxqN2xjMXp3Y0ZnSTlLamJQZkNjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVDeG9tQks1NEZoZ1NxRnVhNWZvR3VQeFhEcjk4L0UraWJDeC9yeHdUSHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZ4R1R4V21aQ0c1UC9mcGlMOFdVVVVQTEZLaVZvWHZmVzZ0bTBJSnErekE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUpBNFBmR3pXaFhLQVBPMFNMM0pIdEJpNHpEYWl0SlhGRXkySmt3Zk4ydz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUjd0clR6VFRwZk5FUnYrMlNQcjVrWDFBZmNMUFgxWFdsV0dJS1RaaWhEOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9IWXBSNDZ5cmtDUzY5RjVxWExzSXlRSXFsK2toR0VFNmFsVWJicWIrWDJWYWM0bmlJdnk3VTlncDgwMHBReWNRR0k2RmZhaCtCangxNHp4SkRNSUJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE4LCJhZHZTZWNyZXRLZXkiOiJ6Tjg4RDY5MFVKdlB5eHNwSUQ4alpZekFtcDhza0JvRkRGS25idE5MRlc4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJjUkVUMEd6UVJwcWRqdi1uTkdrNTBBIiwicGhvbmVJZCI6IjE0ZDBlMzk3LWVjMjktNGMwNi1hM2Y5LWQ3YTYzYWFmNWYwZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJUbWRSOGZrME5ocUJNSzBIUE1teGhoL0doZjA9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiKzdORTkrYWs2SW14bmtqZXZqbVFHZjMrSk5RPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlpOQTVEU1NFIiwibWUiOnsiaWQiOiIyNTY3NjA1NDEwMDE6MTdAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0p5YW9CTVE3ZEdXdWdZWUFpQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjBweTlGekxxQnR0bGtkY0hydU5pam1ZWVBDS3hVQ1AvZ3BQWllnYmNCV1U9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlFjV0llRjVjOGJFdUFrWUxBR0kxZk9CNW5pbDQrQkNBT21rTS9sQ28yOUpFTzRwLzRkZnRFT1RNenNGc2RydlBpTkZkemRQOUYxWDhhYitncTUxK0NBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJUQlR3alJvMWdmQm9JU1g1RXk0SjFJei9OVzJNaXllNkl3Yit6VWQzT0RYakt1VDVEam5ZeXhPcGppNEFzTHR0aEsvNGVkYy9oUEVwZTVSVkJKemlBUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1Njc2MDU0MTAwMToxN0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkS2N2UmN5NmdiYlpaSFhCNjdqWW81bUdEd2lzVkFqLzRLVDJXSUczQVZsIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMyNjE4NDkwfQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "256";
const author = process.env.STICKER_AUTHOR || 'Panda';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '256760541001';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'AUGUNE-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
