/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUhyQjRHVDc5N1E0ZkpCL0lNcDBaS3FzNm1PRU4wZUNIdWhyaG8vV1VsWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0xVZlh2Sm9jbnFZNUVpNjZDZTY0WDRlVnFua3dHczZuaU9ROVpVVXZITT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXTnkyaW82T2VINmRnYjFrVGI5Q1RmVXZVTUhCR1hOa2tDcXpSUzUrTkVZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJwNkF4OFF3WFpGc281ZHRBVit1bndsMi9zTkpibEw4amVsbURmeTZ4bjJvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1KWGRvZlRtTTNWMHlOMXdnN0FkMW1iTkMxVXNqMWZJVEZFVGxid0M3bTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik5seHVMTFF3d1FtTmowajNaMWN2aU1JaGx6VHVSOHg0UWQ0S3cyNGlpeWM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0E4ZTNFeWVDZkdKU0R4Y0p2Mm9QcFVsUXNHdHlhOUgxd2VmanJLQjdVdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidmZvcVNTOXpPUnFBSFIwdStUOG4xTkVCNndVQi9EcWdSWE5rYWM0WUNHST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhrWi83cWNURk1kclVGc2pDaS94R3hOcnZiUkw0NFVMb293amJHczYrdzcrL2FlWkYwelc1dVMvTGJqY1pWVXU4cUtmaHdWdzFuRG9YeDNwVVNvUmlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEwLCJhZHZTZWNyZXRLZXkiOiJCR3hYaFFDQnR0emdZVFRGSEhsdjF5MjhiSkMvc2xZLzlieE1ubVRaeTZRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3Z0NPUWpUNlM3Nk8yS0ZCWElhb2dBIiwicGhvbmVJZCI6IjlkZGZlYTcwLWMzMjUtNDA4Ny1hY2IwLTdmMzQ2ZTBlZWMxYyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFRnFYM2JuWnRTaW9BcDV2R1JmR3RVMzVJY289In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQzdRa0RxVlcxV2lxTXorN29QekpJZ0dPQ1RnPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjU2NVJYNFk1IiwibWUiOnsiaWQiOiIyNTY3NjA1NDEwMDE6MjJAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0orYW9CTVFpTFdldWdZWUF5QUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjBweTlGekxxQnR0bGtkY0hydU5pam1ZWVBDS3hVQ1AvZ3BQWllnYmNCV1U9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjlLRzUwa2lqRzFFUFpsSlg4Qk5PMUFua3NuTWE0NFhnWmRpMmdQeUpEeG9NNVpnbW5uR2c1SWtiMjhtb3p0eUFMQmhWMjJXQzFEbTYxWkFIbk94MUR3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJYbzRSMHBuSnNpTWx5d0pBS0lKN1lyOGphSzBqUzdQS2FFTG9CUjFFYi9jVFFjV2VkMmROdzN2U3hSWnpBS1JiWFlTTDdma2UzSXFCZTN0VlVrNEdqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1Njc2MDU0MTAwMToyMkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkS2N2UmN5NmdiYlpaSFhCNjdqWW81bUdEd2lzVkFqLzRLVDJXSUczQVZsIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMyNzQ1ODc4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUN3YyJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "256";
const author = process.env.STICKER_AUTHOR || 'Panda';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '256760541001';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'AUGUNE-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
